on:
  push:
    tags:
    - '*'

name: Upload Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    env:
      TABULA_JAR: /tmp/tabula.jar
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: curl -sLo ${TABULA_JAR} https://github.com/tabulapdf/tabula-java/releases/download/v1.0.5/tabula-1.0.5-jar-with-dependencies.jar
        name: Download Tabula
      - name: Build 2021/22 2. Halbjahr CSV
        run: |
          cd 2021-22-h2
          ./to-csv.sh 2021-22-h2.csv
      - name: Upload 2021/22 2. Halbjahr PDF to relesae
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 2021-21-h2/statistischedatenzumpandemieverlauf-inkllk.pdf
          asset_name: 2021-22-h2.pdf
          tag: ${{ github.ref }}
      - name: Upload 2021/22 2. Halbjahr PDF to relesae
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 2021-22-h2/2021-22-h2.csv
          asset_name: 2021-21-h2.csv
          tag: ${{ github.ref }}
      